CREATE DATABASE IF NOT EXISTS `nerdflix` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `nerdflix`;

CREATE TABLE peliculas(
	idPelicula  INTEGER  NOT NULL,
	Titulo      VARCHAR(35) NOT NULL,
	Descripcion VARCHAR(779) NOT NULL,
	Estreno     INTEGER  NOT NULL,
	Poster      VARCHAR(34) NOT NULL,
	Trailer     VARCHAR(41) NOT NULL
);

INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (1,'Iron Man','Iron Man (titulada Iron Man: el hombre de hierro en España e Hispanoamérica ) es una película de superhéroes . Es la primera entrega del Universo cinematográfico de Marvel. La cinta fue dirigida por Jon Favreau, con un guion de Stan Lee, Hawk Ostby, Art Marcum y Matt Holloway. Es protagonizada por Robert Downey Jr, Terrence Howard, Jeff Bridges, Shaun Toub y Gwyneth Paltrow. La trama gira en torno a Tony Stark, un empresario e ingeniero, que construye un exoesqueleto motorizado y se convierte en Iron Man, un superhéroe tecnológicamente avanzado.',2008,'https://image.ibb.co/cvofbL/01.jpg','https://www.youtube.com/embed/8hYlB38asDY');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (2,'The Incredible Hulk','The Incredible Hulk (titulada El increíble Hulk en España y Hulk: el hombre increíble en Hispanoamérica) es una película de superhéroes estadounidense de 2008 basada en el personaje Hulk, de Marvel Comics, producida por Marvel Studios y distribuida por Universal Studios. Es la segunda entrega del universo cinematográfico de Marvel. La cinta fue dirigida por Louis Leterrier, con un guion de Zak Penn. Es protagonizada por Edward Norton, Liv Tyler, Tim Roth, Tim Blake Nelson, Ty Burrell y William Hurt.',2008,'https://image.ibb.co/d6YDwL/02.jpg','https://www.youtube.com/embed/xbqNb2PFKKA');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (3,'Iron Man 2','Iron Man 2 es una película de superhéroes estadounidense de 2010 basada en el personaje homónimo de Marvel Comics, producida por Marvel Studios y distribuida por Paramount Pictures.a Es la tercera entrega del universo cinematográfico de Marvel. La cinta fue dirigida por Jon Favreau, con un guión de Justin Theroux. Es protagonizada por Robert Downey Jr., Gwyneth Paltrow, Don Cheadle, Scarlett Johansson, Sam Rockwell, Paul Bettany, Mickey Rourke y Samuel L. Jackson.',2010,'https://image.ibb.co/ghemGL/03.jpg','https://www.youtube.com/embed/wKtcmiifycU');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (4,'Thor','Thor es una película de superhéroes estadounidense de 2011 basada en el personaje homónimo de Marvel Comics, producida por Marvel Studios y distribuida por Paramount Pictures.b Es la cuarta entrega del universo cinematográfico de Marvel. La cinta fue dirigida por Kenneth Branagh, con un guión de Ashley Edward Miller, Zack Stentz y Don Payne. Es protagonizada por Chris Hemsworth, Tom Hiddleston, Natalie Portman, Stellan Skarsgård, Idris Elba, Jaimie Alexander, Colm Feore, Rene Russo, Anthony Hopkins.',2011,'https://image.ibb.co/ntZaAf/04.jpg','https://www.youtube.com/embed/O_dil1dHu2I');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (5,'Captain America: The First Avenger','Capitán América: el primer vengador (título original en inglés: Captain America: The First Avenger) es una película de superhéroes estadounidense de 2011 basada en el personaje homónimo de Marvel Comics, producida por Marvel Studios y distribuida por Paramount Pictures.a Es la quinta entrega del universo cinematográfico de Marvel. La cinta fue dirigida por Joe Johnston, con un guion de Christopher Markus y Stephen McFeely, y protagonizada por Chris Evans, Hugo Weaving, Hayley Atwell, Sebastian Stan, Dominic Cooper, Neal McDonough, Derek Luke, Kenneth Choi, Stanley Tucci, y Tommy Lee Jones.',2011,'https://image.ibb.co/iv82qf/05.jpg','https://www.youtube.com/embed/-J3HfllvXWE');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (6,'The Avengers','The Avengers (titulada The Avengers: Los Vengadores en Hispanoamérica y Marvel Los Vengadores en España) es una película estadounidense de superhéroes de 2012 escrita y dirigida por Joss Whedon. Fue producida por Marvel Studios y distribuida por Walt Disney Pictures, y basada en el cómic homónimo de Marvel Comics. Es parte del Universo cinematográfico de Marvel, que enlaza varias películas de superhéroes de Marvel como Iron Man (2008), El increíble Hulk (2008), Iron Man 2 (2010), Thor (2011) y Capitán América: el primer vengador (2011). La película cuenta con un reparto coral, que incluye a Robert Downey Jr., Chris Hemsworth, Tom Hiddleston, Mark Ruffalo, Chris Evans, Scarlett Johansson, Jeremy Renner, Clark Gregg, Cobie Smulders, y Samuel L. Jackson.',2012,'https://image.ibb.co/eTQFAf/06.jpg','https://www.youtube.com/embed/eOrNdBpGMv8');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (7,'Iron Man 3','Iron Man 3 es una película estadounidense sobre el superhéroe Iron Man, de Marvel Comics, producida por Marvel Studios y distribuida por Walt Disney Pictures. Es la secuela de Iron Man (2008) y Iron Man 2 (2010), y es la primera película con la que se dio inicio a la segunda fase del universo cinematográfico de Marvel, siendo el primer gran estreno de la franquicia después de The Avengers (2012) que fue la sexta y última película de la primera fase del ya mencionado universo cinematográfico.',2013,'https://image.ibb.co/jOARGL/07.jpg','https://www.youtube.com/embed/6Cl8PmVm3YE');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (8,'Thor: The Dark World','Thor: The Dark World (titulada Thor: Un Mundo Oscuro en Hispanoamérica y Thor: El Mundo Oscuro en España) es una película de superhéroes estadounidense basada en el personaje homónimo de Marvel Comics: Thor, producida por Marvel Studios y distribuida por Walt Disney Studios Motion Pictures. Se trata de la secuela del largometraje Thor (2011) y la octava entrega en el Universo Cinematográfico de Marvel. Dirigida por Alan Taylor que dio vida al guión de Christopher Yost, Christopher Markus y Stephen McFeely y producida por Kevin Feige. Protagonizada por Chris Hemsworth, Tom Hiddleston, Natalie Portman, Idris Elba, Stellan Skarsgård, Christopher Eccleston, Jaimie Alexander, Adewale Akinnuoye-Agbaje, Ray Stevenson, Zachary Levi, Kat Dennings, Rene Russo, y Anthony Hopkins.',2013,'https://image.ibb.co/dbm0bL/08.jpg','https://www.youtube.com/embed/npvJ9FTgZbM');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (9,'Captain America: The Winter Soldier','Captain America: The Winter Soldier (titulada Capitán América: el Soldado de Invierno en España y Capitán América y el Soldado del Invierno en Hispanoamérica)2 es una película de superhéroes y Acción del universo cinematográfico de Marvel estrenada el 4 de abril de 2014. Es una secuela directa de The Avengers y también enlaza con lo sucedido en Capitán América: el primer vengador. La película está dirigida por los hermanos Anthony y Joe Russo y protagonizada por Chris Evans, Samuel L. Jackson, Scarlett Johansson, Sebastian Stan, Anthony Mackie y Robert Redford y nominada al Oscar por mejores efectos especiales.',2014,'https://image.ibb.co/itumGL/09.jpg','https://www.youtube.com/embed/82RKQPgeYRs');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (10,'Guardians of the Galaxy','Guardianes de la Galaxia (título original en inglés, Guardians of the Galaxy) es una película de superhéroes realizada por Estudios Marvel y es la décima película del universo cinematográfico de Marvel. Dirigida por James Gunn, quien también escribe el guión junto con Nicole Perlman y cuenta con un reparto coral, que incluye a Chris Pratt, Zoe Saldana, Bradley Cooper, Dave Bautista, Vin Diesel, Michael Rooker, Karen Gillan, Djimon Hounsou, John C. Reilly, Glenn Close, Lee Pace, Benicio del Toro.',2014,'https://image.ibb.co/czjmGL/10.jpg','https://www.youtube.com/embed/2XltzyLcu0g');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (11,'Avengers: Age of Ultron','Avengers: Age of Ultron (titulada Avengers: Era de Ultrón en Hispanoamérica y Vengadores: La era de Ultrón en España) es una película de superhéroes, secuela de The Avengers, dirigida por Joss Whedon y producida por Kevin Feige. Forma parte de la segunda fase del universo cinematográfico de Marvel, junto con Iron Man 3, Thor: The Dark World, Captain America: The Winter Soldier, Guardianes de la Galaxia y Ant Man: El Hombre Hormiga. El elenco es el mismo de la anterior con la inclusión de la Bruja Escarlata, Quicksilver2 y Visión.',2015,'https://image.ibb.co/e3xTVf/11.jpg','https://www.youtube.com/embed/hpazy0BHzxY');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (12,'Ant-Man','Ant-Man (titulada Ant-Man: el hombre hormiga en Hispanoamérica) es una película de superhéroes estadounidense estrenada el 17 de julio de 2015.3 Está dirigida por Peyton Reed4 y se basa en el personaje homónimo perteneciente a Marvel Comics. Es la decimosegunda película de Marvel Studios y también la película que cierra la segunda fase del Universo cinematográfico de Marvel.',2015,'https://image.ibb.co/derBi0/12.jpg','https://www.youtube.com/embed/QfOZWGLT1JM');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (13,'Capitán América: Civil War','Capitán América: Civil War (originalmente en inglés: Captain America: Civil War) es una película de superhéroes estadounidense, estrenada el 27 de abril de 2016. Es una secuela de Captain America: The Winter Soldier, siendo la que completa la Trilogía de Capitán América, y es la película que inicia la Fase 3 del Universo cinematográfico de Marvel. Está dirigida por los hermanos Anthony y Joe Russo, y cuenta con un reparto coral con Chris Evans, Robert Downey Jr., Scarlett Johansson, Sebastian Stan, Anthony Mackie, Emily VanCamp, Don Cheadle, Jeremy Renner, Chadwick Boseman, Paul Bettany, Elizabeth Olsen, Paul Rudd, Frank Grillo, Tom Holland, William Hurt, Martin Freeman y Daniel Brühl.',2016,'https://image.ibb.co/bNTri0/13.jpg','https://www.youtube.com/embed/FkTybqcX-Yo');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (14,'Doctor Strange','Doctor Strange (titulada Doctor Strange: Hechicero Supremo en Hispanoamérica) es una película estadounidense de superhéroes, basada en el personaje de Marvel Comics del mismo nombre, producida por Marvel Studios y distribuida por Walt Disney Studios Motion Pictures en 2016. Es la decimocuarta película del Universo cinematográfico de Marvel (UCM). La película es dirigida por Scott Derrickson, con un guion escrito por Derrickson, Jon Spaihts y C. Robert Cargill. Cuenta con los actores Benedict Cumberbatch, Mads Mikkelsen, Chiwetel Ejiofor, Rachel McAdams, Benjamin Bratt, Benedict Wong, y Tilda Swinton.',2016,'https://image.ibb.co/kmdfbL/14.jpg','https://www.youtube.com/embed/HSzx-zryEgM');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (15,'Guardians of the Galaxy Vol. 2','Guardianes de la Galaxia Volumen 2 es una película estadounidense de superhéroes basada en el equipo de superhéroes Guardianes de la Galaxia de Marvel Comics, producida por Marvel Studios y distribuida por Walt Disney Studios Motion Pictures. Es la secuela de la cinta de 2014 Guardianes de la Galaxia y la decimoquinta película en el Universo cinematográfico de Marvel. La película esta escrita y dirigida por James Gunn y con las actuaciones de Chris Pratt, Zoe Saldaña, Dave Bautista, Vin Diesel, Bradley Cooper, Michael Rooker, Karen Gillan y Kurt Russell.',2017,'https://image.ibb.co/cB98Vf/15.jpg','https://www.youtube.com/embed/2cv2ueYnKjg');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (16,'Spider-Man: Homecoming','Spider-Man: Homecoming1 2 (El Hombre Araña: De regreso a casa en Hispanoamérica3 ) es una próxima película estadounidense de superhéroes, basada en el cómic homónimo del personaje de Spider-Man, producida por Marvel Studios y Columbia Pictures, y distribuida por Sony Pictures Entertainment. Está destinada a ser el tercer reinicio de la franquicia de Spider-Man y la decimosexta película del Universo cinematográfico de Marvel. La película es dirigida por Jon Watts, con un guion de John Francis Daley & Jonathan M. Goldstein y Christopher Ford & Jon Watts, y está protagonizada por Tom Holland, Michael Keaton, Donald Glover, Zendaya, Tyne Daly, Tony Revolori, Jon Favreau, Marisa Tomei, Robert Downey Jr.',2017,'https://image.ibb.co/bvmoVf/16.jpg','https://www.youtube.com/embed/n9DwoQ7HWvI');
INSERT INTO peliculas (idPelicula,Titulo,Descripcion,Estreno,Poster,Trailer) VALUES (17,'Thor: Ragnarok','Thor: Ragnarok es una película de superhéroes estadounidense basada en el personaje homónimo de Marvel Comics: Thor, producida por Marvel Studios y distribuida por Walt Disney Studios Motion Pictures. Se trata de la tercera parte de la trilogía de Thor, siendo la secuela del largometraje Thor: The Dark World (2013) y formando parte de la tercera fase dentro del Universo Cinematográfico de Marvel. Dirigida por Taika Waititi, dando vida al guion de Eric Pearson y producida por Kevin Feige. Está protagonizada por Chris Hemsworth, Tom Hiddleston, Cate Blanchett, Idris Elba, Jeff Goldblum, Tessa Thompson, Karl Urban, Mark Ruffalo, Benedict Cumberbatch y Anthony Hopkins.',2017,'https://image.ibb.co/h6uLbL/17.jpg','https://www.youtube.com/embed/JBxQ_XYQJhc');

ALTER TABLE `peliculas`
  ADD PRIMARY KEY (`idPelicula`);

ALTER TABLE `peliculas`
  MODIFY `idPelicula` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
COMMIT;